services:
  monitoring-api:
    image: "ghcr.io/dcsg2003-v25-8/monitoring-api:latest"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - "swarm"
    environment:
      PORT: "${PORT:-8080}"
      API_KEY: "${API_KEY}"
      OS_PASSWORD: "${OS_PASSWORD}"
    command:
      - "gunicorn"
      - "main:app"
      - "--worker-class"
      - "uvicorn.workers.UvicornWorker"
      - "--timeout"
      - "120"
      - "--graceful-timeout"
      - "120"
      - "--workers"
      - "2"
      - "--bind"
      - "0.0.0.0:${PORT:-8080}"

networks:
  swarm:
    external: true
