services:
  bookface:
    image: "ghcr.io/dcsg2003-v25-8/bookface:latest"
    deploy:
      replicas: 2
      placement:
        constraints:
          - "engine.labels.role == worker"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - "swarm"
    environment:
      BF_DB_HOST: "192.168.128.253"
      BF_DB_PORT: "26257"
      BF_DB_NAME: "${BF_DB_NAME:-bf}"
      BF_DB_USER: "${BF_DB_USER:-bfuser}"
      BF_DB_PASS: "${BF_DB_PASS:-}"
      BF_WEBHOST: "${BF_WEBHOST:-10.20.0.43}"
      BF_FRONTPAGE_LIMIT: "500"
      BF_MEMCACHE_SERVER: "memcached"

networks:
  swarm:
    external: true
