services:
  memcached:
    image: "memcached:latest"
    hostname: "memcached"
    deploy:
      replicas: 1
      pleacment:
        constraints:
          - "engine.labels.role == worker"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - "swarm"

    # command:
    #   - --conn-limit=1024
    #   - --memory-limit=64
    #   - --threads=4

networks:
  swarm:
    exsternal: true
