services:
  nginx:
    image: "nginx:latest"
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.labels.webserver == true"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - "swarm"

networks:
  swarm:
    external: true
