services:
  nginx:
    image: "nginx:latest"
    deploy:
      replicas: 2
      placement:
        constraints:
          - "engine.labels.role == worker"
        max_replicas_per_node: 1
        preferences:
          - spread: "node.hostname"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - "swarm"

networks:
  swarm:
    external: true
