services:
  varnish:
    image: "varnish:stable"
    hostname: "varnish"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "engine.labels.role == ingress"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - "swarm"
    environment:
      VARNISH_SIZE: "1G"
    tmpfs:
      - "/var/lib/varnish:exec"
    configs:
      - source: "varnish"
        target: "/etc/varnish/default.vcl"
    # healthcheck:
    #   test: [ "CMD", "curl", "--fail", "http://localhost" ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3

configs:
  varnish:
    # NOTE This is necessary because docker doesn't redeploy configs.
    #   $ CFG=1 docker stack deploy -c docker-stack.yml haproxy
    name: "default.vcl-v${CFG:-0}"
    file: ./default.vcl

networks:
  swarm:
    external: true
