name: Deploy Images to GHCR

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'The stack to deploy'
        required: true
        type: choice
        options:
          - bookface

jobs:
  push-bookface-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: './${{inputs.stack}}'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{inputs.stack}}"
          push: true
          tags: ghcr.io/dcsg2003-v25-8/${{inputs.stack}}:latest


