name: Deploy Images to GHCR

on:
  workflow_dispatch:

jobs:
      push-bookface-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './bookface'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/DCSG2003-V25-8/bookface:latest
              docker push ghcr.io/DCSG2003-V25-8/bookface:latest


